---
- block:

    - name: Install python / pip / ansible dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - libffi-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - python-dev
        - zlib1g-dev
      become: yes
      tags: ["ansible","apt"]

    - name: Remove python-cffi and python-pip for compatibility
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      with_items:
        - python-cffi
        - python-pip
      become: yes
      tags: ["ansible","apt"]

    - name: Install pip with easy_install
      easy_install:
        name: pip
      become: yes
      tags: ["ansible","pip"]

    - name: Install ansible with pip
      pip:
        name: ansible
        version: "{{ __ansible_version|default(omit) }}"
      become: yes
      tags: ["ansible","pip"]

  when: __ansible_pip|bool == True

- block:

    - block:

        - name: Set ansible package name with version (for apt)
          set_fact:
            __ansible_package_name: "{{ __ansible_package_name }}={{ __ansible_version }}"
          when: (__ansible_version is defined) and
                (__ansible_version|string != "")

        - name: Install ansible with apt
          apt:
            name: "{{ __ansible_package_name }}"
            state: present
          become: yes
          tags: ["ansible","apt"]

      when: ansible_os_family == "Debian"

    - block:

        - name: Set ansible package name with version (for yum)
          set_fact:
            __ansible_package_name: "{{ __ansible_package_name }}-{{ __ansible_version }}"
          when: (__ansible_version is defined) and
                (__ansible_version|string != "")

        - name: Install EPEL with yum
          yum:
            name: "epel-release"
            state: present
          become: yes
          register: install_epel
          tags: ["ansible","yum"]

        - name: Update yum cache
          yum:
            update_cache: yes
          become: yes
          when: install_epel.changed == True
          tags: ["ansible","yum"]

        - name: Install ansible with yum
          yum:
            name: "ansible-{{ ansible_version }}"
            state: present
          become: yes
          tags: ["ansible","yum"]

      when: ansible_os_family == "RedHat"

  when: __ansible_pip|bool == False
